import assert from 'node:assert/strict'

// Runs in the shared, fully intercepted context. No live service is contacted.
export async function checkComparison({page,visit,shot,checked,apiCalls}) {
 const cards=()=>page.getByRole('region',{name:'Períodos em comparação'}).locator(':scope > div')
 const ready=async()=>{
  await page.getByRole('heading',{name:'Resultado dos períodos',exact:true}).waitFor()
  await page.waitForFunction(()=>!document.querySelector('header.page-heading button:disabled'))
 }
 const totals=async(a,b)=>{
  assert.match(await cards().nth(0).innerText(),new RegExp(a.replace('.', '\\.')))
  assert.match(await cards().nth(1).innerText(),new RegExp(b.replace('.', '\\.')))
 }
 await page.setViewportSize({width:1440,height:1000})
 await visit('/comparativo','Comparativo');await ready()
 await totals('8.250,00','7.550,00')
 assert.match(await cards().nth(0).innerText(),/8 vendas/)
 assert.match(await cards().nth(1).innerText(),/7 vendas/)
 assert.match(await page.getByRole('row',{name:/^Receita operacional/}).innerText(),/\+R\$\s*700,00/)
 await page.getByText(/Fora deste gráfico por falta de horário exato: 1 registros em A e 0 em B/).waitFor()
 checked('Comparison days preserves confirmed source totals and unlinked manual once; linked manual excluded')
 const before=apiCalls.length
 await page.getByLabel(/^Família/).selectOption('DevClub')
 await totals('2.500,00','1.800,00')
 assert.equal(apiCalls.length,before,'Comparison family filter refetched APIs')
 await page.getByLabel(/^Produto/).selectOption('DevClub QA comparação')
 await totals('700,00','0,00')
 assert.match(await page.getByRole('row',{name:/^Receita operacional/}).innerText(),/Base B igual a zero/)
 await page.getByRole('button',{name:'Limpar filtros',exact:true}).click()
 await totals('8.250,00','7.550,00')
 checked('Comparison family/original filters local and zero-base percentage explicit')
 for(const width of [1440,360]){
  await page.setViewportSize({width,height:1000})
  for(const dark of [false,true]){
   if(await page.evaluate(()=>document.documentElement.classList.contains('dark'))!==dark)await page.getByRole('button',{name:dark?'Usar tema escuro':'Usar tema claro'}).click()
   assert.equal(await page.evaluate(()=>document.documentElement.classList.contains('dark')),dark)
   await shot(`comparison-days-${dark?'dark':'light'}-${width}`)
  }
 }
 await page.getByRole('button',{name:'Barras',exact:true}).click()
 assert.equal(await page.getByRole('button',{name:'Barras',exact:true}).getAttribute('aria-pressed'),'true')
 await page.getByRole('button',{name:'Intervalos',exact:true}).click()
 await page.getByLabel('Início do período A').fill('2026-09-09')
 await page.getByLabel('Fim do período A').fill('2026-09-15')
 await page.getByLabel('Início do período B').fill('2026-09-01')
 await page.getByLabel('Fim do período B').fill('2026-09-08')
 const invalidBefore=apiCalls.length
 await page.getByRole('button',{name:'Comparar períodos'}).click()
 await page.getByRole('alert').filter({hasText:'mesma duração'}).waitFor()
 assert.equal(apiCalls.length,invalidBefore,'Invalid duration fetched sources')
 await page.getByLabel('Início do período B').fill('2026-09-02')
 await page.getByRole('button',{name:'Comparar períodos'}).click()
 await page.getByRole('heading',{name:'Receita ao longo dos períodos',exact:true}).waitFor();await ready()
 await totals('8.250,00','7.550,00')
 assert.match(await cards().nth(0).innerText(),/7 dias/)
 await page.locator('summary').filter({hasText:'Perfil por hora e alinhamento dos dias'}).click()
 const alignment=page.locator('details').filter({has:page.locator('summary').filter({hasText:'Perfil por hora e alinhamento dos dias'})})
 assert.equal(await alignment.locator('tbody tr').count(),7)
 assert.match(await alignment.locator('tbody tr').first().innerText(),/09\/09\/2026.*02\/09\/2026/)
 assert.match(await alignment.locator('tbody tr').last().innerText(),/15\/09\/2026.*08\/09\/2026.*700,00/)
 await page.locator('summary').filter({hasText:'Perfil por hora e alinhamento dos dias'}).click()
 for(const dark of [false,true]){
  if(await page.evaluate(()=>document.documentElement.classList.contains('dark'))!==dark)await page.getByRole('button',{name:dark?'Usar tema escuro':'Usar tema claro'}).click()
  await shot(`comparison-periods-${dark?'dark':'light'}-360`)
 }
 await page.getByRole('button',{name:'Atualizar fontes'}).click();await ready()
 await totals('8.250,00','7.550,00')
 checked('Comparison intervals validate equal duration, align seven days, preserve totals after refresh')
 await page.getByRole('button',{name:'Inverter períodos'}).click()
 await page.getByRole('button',{name:'Comparar períodos'}).click();await ready()
 await totals('7.550,00','8.250,00')
 checked('Comparison inversion updates A/B without duplicating manual ledger')
 const sidebar=page.locator('#workspace-navigation')
 const opener=page.getByRole('button',{name:'Abrir menu',exact:true})
 assert.equal(await sidebar.evaluate(node=>node.inert),true)
 await sidebar.locator('a').first().evaluate(node=>node.focus())
 assert.equal(await sidebar.evaluate(node=>node.contains(document.activeElement)),false,'Closed sidebar accepted focus')
 await opener.focus();await page.keyboard.press('Tab')
 assert.equal(await sidebar.evaluate(node=>node.contains(document.activeElement)),false,'Tab entered inert sidebar')
 await opener.focus();await page.keyboard.press('Enter')
 await page.getByRole('dialog',{name:'Menu principal'}).waitFor()
 assert.equal(await sidebar.evaluate(node=>node.inert),false)
 assert.equal(await sidebar.locator('a').first().evaluate(node=>node===document.activeElement),true)
 await page.keyboard.press('Shift+Tab')
 assert.equal(await page.getByRole('button',{name:'Sair do sistema'}).evaluate(node=>node===document.activeElement),true)
 await page.keyboard.press('Tab')
 assert.equal(await sidebar.locator('a').first().evaluate(node=>node===document.activeElement),true)
 await shot('mobile-menu-dark-360')
 await page.keyboard.press('Escape')
 assert.equal(await opener.getAttribute('aria-expanded'),'false')
 assert.equal(await opener.evaluate(node=>node===document.activeElement),true)
 assert.equal(await sidebar.evaluate(node=>node.inert),true)
 assert.notEqual(await page.evaluate(()=>document.body.style.overflow),'hidden')
 checked('Mobile menu inert when closed; keyboard trap wraps; Escape restores focus and scroll')
}
