/* eslint-disable react/prop-types -- Internal React 19 components with explicit props. */
import { lazy, Suspense, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowUpRight, Target, Save } from 'lucide-react'
import { useAuth } from '../contexts/AuthContext'
import { requestApi } from '../lib/api'
import { PageSkeleton } from '../components/WorkspaceLayout'
const HubGoals=lazy(()=>import('./HubGoals'))
const MONTHS=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro']
const PRODUCTS=['all','MBA','DevClub','IAClub','Seu segundo salário com IA','Outros']
const METRICS={operational:'Valor operacional',gross:'Valor bruto',net:'Valor líquido',cash:'Caixa recebido',count:'Quantidade de vendas'}
const empty=product=>({product,metric:'operational',target:0,superTarget:0,ultraTarget:0,paceBasis:'calendar',notes:''})
export default function GoalsPage(){
 const {userRoles,hasPermission}=useAuth();const admin=userRoles?.isAdmin
 const [year,setYear]=useState(new Date().getFullYear()),[month,setMonth]=useState(new Date().getMonth()+1),[tab,setTab]=useState('products'),[metric,setMetric]=useState('operational'),[plans,setPlans]=useState([]),[drafts,setDrafts]=useState({}),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(null),[message,setMessage]=useState(''),[revision,setRevision]=useState(0)
 useEffect(()=>{if(tab!=='products')return;const controller=new AbortController();setLoading(true);setDrafts({});setError('');setMessage('');requestApi(`/goal-plans/${year}/${month}`,{signal:controller.signal}).then(({plans})=>{if(controller.signal.aborted)return;setPlans(plans);setDrafts(Object.fromEntries(PRODUCTS.map(product=>[product,plans.find(p=>p.product===product&&p.metric===metric)||{...empty(product),metric}])))}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[year,month,metric,revision,tab])
 const change=(product,key,value)=>setDrafts(current=>{const next={...current[product],[key]:value};if(key==='target'){next.superTarget=Math.max(value,next.superTarget);next.ultraTarget=Math.max(next.superTarget,next.ultraTarget)}if(key==='superTarget')next.ultraTarget=Math.max(value,next.ultraTarget);return {...current,[product]:next}})
 const save=async product=>{setSaving(product);setError('');setMessage('');try{const result=await requestApi(`/goal-plans/${year}/${month}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(drafts[product])});setPlans(prev=>[...prev.filter(p=>!(p.product===product&&p.metric===metric)),result.plan]);setMessage(`Meta de ${product==='all'?'todos os produtos':product} salva.`)}catch(e){setError(e.message)}finally{setSaving(null)}}
 return <div className="hub-page"><header className="page-heading"><div><h1>Metas da operação</h1><p>Defina o resultado esperado do negócio, de cada produto e da equipe.</p></div>{hasPermission('goal-pace')&&<Link className="button button-primary" to={`/pace?year=${year}&month=${month}`}><ArrowUpRight size={17}/>Acompanhar o ritmo</Link>}</header><div className="tab-strip" role="tablist" aria-label="Grupo de metas">{[['products','Negócio e produtos'],['team','Time comercial'],['finance','Receita por pagamento']].map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div>
 {tab==='team'?<Suspense fallback={<PageSkeleton/>}><HubGoals/></Suspense>:<><div className="filter-bar"><label>Mês<select value={month} onChange={e=>setMonth(+e.target.value)}>{MONTHS.map((name,index)=><option key={name} value={index+1}>{name}</option>)}</select></label><label>Ano<input type="number" min="2000" max="2100" value={year} onChange={e=>{const value=+e.target.value;if(value>=2000&&value<=2100)setYear(value)}}/></label>{tab==='products'&&<label>Indicador<select value={metric} onChange={e=>setMetric(e.target.value)}>{Object.entries(METRICS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>}</div>
 {tab==='finance'?<RevenueGoals year={year} month={month} admin={admin}/>:<>
 <div className="notice">{metric==='operational'?'O valor operacional preserva o critério atual de cada plataforma. Para comparações estritas, escolha bruto, líquido ou caixa; essas métricas podem não estar disponíveis em todas as fontes.':'A comparação considera apenas valores que a fonte informa para este indicador.'} A meta geral é independente da soma das metas por produto. Ritmo por dias úteis considera segunda a sexta, sem feriados.</div>
 {error&&<div className="notice notice-error" role="alert">{error}<button className="underline ml-3" onClick={()=>setRevision(v=>v+1)}>Tentar novamente</button></div>}{message&&<div className="notice" role="status">{message}</div>}
 {loading?<PageSkeleton/>:!error||Object.keys(drafts).length?<div className="space-y-4">{PRODUCTS.map(product=>{const draft=drafts[product];if(!draft)return null;const saved=plans.find(p=>p.product===product&&p.metric===metric);return <section key={product} className="surface-panel"><header className="flex items-center justify-between gap-3 mb-5"><div className="flex items-center gap-3"><Target size={21} className="text-primary"/><div><h2 className="text-lg">{product==='all'?'Meta geral':product}</h2><p className="text-xs text-muted-foreground">{saved?`Atualizada em ${new Date(saved.updatedAt).toLocaleString('pt-BR')}`:'Ainda não configurada'}</p></div></div>{admin&&<button className="button" disabled={saving!==null} onClick={()=>save(product)}><Save size={15}/>{saving===product?'Salvando…':'Salvar'}</button>}</header><fieldset disabled={!admin||saving!==null}><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">{[['target','Meta base'],['superTarget','Supermeta'],['ultraTarget','Ultrameta']].map(([key,label])=><label key={key} className="ds-label">{label} {metric!=='count'&&'(R$)'}<input className="ds-input mt-2" type="number" min="0" max="999999999999" step={metric==='count'?'1':'.01'} value={draft[key]} onChange={e=>change(product,key,e.target.value===''?'':Number(e.target.value))}/></label>)}<label className="ds-label">Distribuição do ritmo<select className="ds-input mt-2" value={draft.paceBasis} onChange={e=>change(product,'paceBasis',e.target.value)}><option value="calendar">Dias corridos</option><option value="business">Dias úteis</option></select></label></div><label className="ds-label mt-4">Observações<input className="ds-input mt-2" maxLength={2000} value={draft.notes} onChange={e=>change(product,'notes',e.target.value)} placeholder="Premissas, campanha ou objetivo deste mês"/></label></fieldset></section>})}</div>:null}</>}
 </>}
 </div>
}
function RevenueGoals({year,month,admin}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{let active=true;setData(null);setError('');requestApi(`/goals/revenue/month/${year}/${month}`).then(result=>{if(active)setData(result.data)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[year,month])
 const save=async()=>{setSaving(true);setError('');try{await requestApi(`/goals/revenue/month/${year}/${month}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});setMessage('Metas financeiras salvas.')}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <section className="surface-panel space-y-5"><h2 className="text-lg">Receita por meio de pagamento</h2><p className="text-sm text-muted-foreground">Metas financeiras existentes, preservadas no banco do Dashboard.</p>{error&&<p role="alert" className="notice notice-error">{error}</p>}{message&&<p role="status">{message}</p>}{!data&&!error?<PageSkeleton/>:data&&<><fieldset disabled={!admin||saving} className="space-y-5">{[['faturamentoCartao','Faturamento no cartão'],['faturamentoBoleto','Faturamento no boleto'],['investimentoTrafego','Orçamento de aquisição']].map(([key,label])=><div key={key}><h3 className="text-sm mb-2">{label}</h3><div className="grid grid-cols-1 sm:grid-cols-3 gap-3">{['base','super','ultra'].map(level=><label key={level} className="ds-label">{level==='base'?'Meta base':level==='super'?'Supermeta':'Ultrameta'} (R$)<input className="ds-input mt-2" type="number" min="0" step=".01" value={data[key]?.[level]??0} onChange={e=>setData({...data,[key]:{...data[key],[level]:Number(e.target.value)}})}/></label>)}</div></div>)}</fieldset>{admin&&<button className="button button-primary" disabled={saving} onClick={save}>{saving?'Salvando…':'Salvar metas financeiras'}</button>}</>}</section>
}
