import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BookOpen, File, Link2, Folder, Plus, Pencil, Trash2, ExternalLink, Upload } from 'lucide-react'
import { useAuth } from '../contexts/AuthContext'
import { supabase } from '../hub/integrations/supabase/client'
import { API_URL, apiFetch, requestApi } from '../lib/api'
import Dialog from '../components/Dialog'
const EMPTY={title:'',description:'',category:'Geral',url:'',type:'document'}
const NO_MATERIALS=[]
export default function MaterialsPage(){
 const {userRoles}=useAuth(),admin=userRoles?.isAdmin,qc=useQueryClient()
 const [category,setCategory]=useState('all'),[search,setSearch]=useState(''),[editing,setEditing]=useState(null),[file,setFile]=useState(null),[mode,setMode]=useState('link'),[error,setError]=useState(''),[remove,setRemove]=useState(null),[opening,setOpening]=useState(null)
 const query=useQuery({queryKey:['materials'],queryFn:async()=>{const {data,error}=await supabase.from('materials').select('*').order('created_at',{ascending:false});if(error)throw error;return data||[]}})
 const materials=query.data||NO_MATERIALS
 const categories=useMemo(()=>[...new Set(materials.map(m=>m.category||'Geral'))].sort((a,b)=>a.localeCompare(b,'pt-BR')),[materials])
 const filtered=materials.filter(m=>(category==='all'||m.category===category)&&`${m.title} ${m.description} ${m.category}`.toLowerCase().includes(search.toLowerCase()))
 const save=useMutation({mutationFn:async()=>{
  if(!editing.title.trim()||!editing.category.trim())throw new Error('Preencha o título e a categoria.')
  let url=editing.url.trim(),type=editing.type
  if(file){if(file.size>20*1024*1024)throw new Error('O limite é de 20 MB por arquivo.');const response=await apiFetch(`${API_URL}/hub/materials/upload?name=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream'},body:file});const data=await response.json();if(!response.ok)throw new Error(data.error||'Falha ao enviar o arquivo.');url=data.url;type='document'}
  if(!url.startsWith('storage://materials/')){let parsed;try{parsed=new URL(url)}catch{throw new Error('Informe um link válido ou envie um arquivo.')}if(!['https:','http:'].includes(parsed.protocol))throw new Error('Use um link HTTP ou HTTPS.')}
  const data={title:editing.title.trim(),description:editing.description.trim(),category:editing.category.trim(),url,type}
  const result=editing.id?await supabase.from('materials').update(data).eq('id',editing.id):await supabase.from('materials').insert(data)
  if(result.error)throw result.error
 },onSuccess:()=>{qc.invalidateQueries({queryKey:['materials']});setEditing(null);setFile(null);setError('')},onError:e=>setError(e.message)})
 const deletion=useMutation({mutationFn:async()=>{const {error}=await supabase.from('materials').delete().eq('id',remove.id);if(error)throw error},onSuccess:()=>{qc.invalidateQueries({queryKey:['materials']});setRemove(null)},onError:e=>setError(e.message)})
 const open=async material=>{setOpening(material.id);setError('');const tab=window.open('about:blank','_blank');if(tab)tab.opener=null;try{const result=await requestApi(`/hub/materials/${material.id}/open`);if(tab)tab.location.href=result.url;else window.location.assign(result.url)}catch(e){tab?.close();setError(e.message)}finally{setOpening(null)}}
 return <div className="hub-page"><header className="page-heading"><div><h1>Biblioteca de materiais</h1><p>Playbooks, treinamentos e documentos organizados em um único lugar.</p></div>{admin&&<button className="button button-primary" onClick={()=>{setEditing({...EMPTY,category:category==='all'?'Geral':category});setFile(null);setMode('file');setError('')}}><Plus size={17}/>Adicionar material</button>}</header>
  <div className="filter-bar"><label>Buscar<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Título, descrição ou categoria"/></label><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Todas as categorias</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><span className="text-sm text-muted-foreground">{filtered.length} materiais</span></div>
  {(error||query.error)&&<div className="notice notice-error" role="alert">{error||query.error.message}<button className="underline ml-3" onClick={()=>query.refetch()}>Atualizar</button></div>}
  {query.isPending?<div className="skeleton skeleton-chart" role="status" aria-label="Carregando materiais"/>:!filtered.length?<div className="surface-panel empty-state"><BookOpen className="mx-auto"/><h2>{materials.length?'Nenhum material encontrado':'Sua biblioteca começa aqui'}</h2><p>{admin?'Adicione um link ou envie um arquivo. Crie categorias ao salvar para organizar o conteúdo.':'Os materiais compartilhados pelo gestor aparecerão aqui.'}</p></div>:<div className="surface-panel p-0 overflow-hidden"><div className="table-responsive"><table className="data-table"><thead><tr><th>Material</th><th>Categoria</th><th>Adicionado em</th><th>Ações</th></tr></thead><tbody>{filtered.map(m=><tr key={m.id}><td><div className="flex items-start gap-3">{m.url.startsWith('storage:')?<File size={20}/>:<Link2 size={20}/>}<div><strong>{m.title}</strong><p className="text-sm text-muted-foreground mt-1 max-w-lg">{m.description}</p></div></div></td><td><span className="flex items-center gap-2"><Folder size={14}/>{m.category}</span></td><td className="whitespace-nowrap">{new Date(m.created_at).toLocaleDateString('pt-BR')}</td><td><div className="flex items-center gap-1"><button className="button btn-sm" disabled={opening===m.id} onClick={()=>open(m)}><ExternalLink size={14}/>Abrir</button>{admin&&<><button className="icon-button" title="Editar material e categoria" aria-label={`Editar ${m.title}`} onClick={()=>{setEditing({...m});setFile(null);setMode(m.url.startsWith('storage:')?'file':'link');setError('')}}><Pencil size={16}/></button><button className="icon-button" aria-label={`Excluir ${m.title}`} onClick={()=>{setRemove(m);setError('')}}><Trash2 size={16}/></button></>}</div></td></tr>)}</tbody></table></div></div>}
  {editing&&<Dialog title={editing.id?'Editar material':'Adicionar material'} onClose={()=>{if(!save.isPending)setEditing(null)}}><form onSubmit={e=>{e.preventDefault();save.mutate()}} className="space-y-5"><div className="form-grid"><label className="form-wide">Título<input className="ds-input" required maxLength={180} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label className="form-wide">Descrição<textarea className="ds-input" rows={3} maxLength={2000} value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label className="form-wide">Categoria<input className="ds-input" list="material-categories" required maxLength={80} value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}/><datalist id="material-categories">{categories.map(c=><option key={c} value={c}/>)}</datalist><small>Escolha uma existente ou digite uma nova.</small></label></div><div className="tab-strip" role="tablist" aria-label="Origem do material"><button type="button" role="tab" aria-selected={mode==='file'} onClick={()=>setMode('file')}>Enviar arquivo</button><button type="button" role="tab" aria-selected={mode==='link'} onClick={()=>{setMode('link');setFile(null)}}>Link externo</button></div>{mode==='file'?<label className="block text-sm"><span className="flex items-center gap-2 mb-2"><Upload size={16}/>Arquivo de até 20 MB</span><input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.csv,.docx,.xlsx,.pptx" onChange={e=>setFile(e.target.files?.[0]||null)}/>{editing.url.startsWith('storage:')&&!file&&<p className="mt-2 text-muted-foreground">O arquivo atual será mantido.</p>}</label>:<label className="ds-label">Endereço<input className="ds-input mt-2" type="url" required value={editing.url.startsWith('storage:')?'':editing.url} onChange={e=>setEditing({...editing,url:e.target.value,type:'link'})} placeholder="https://"/></label>}{error&&<p className="notice notice-error" role="alert">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className="button" disabled={save.isPending} onClick={()=>setEditing(null)}>Cancelar</button><button className="button button-primary" disabled={save.isPending}>{save.isPending?'Salvando…':'Salvar material'}</button></div></form></Dialog>}
  {remove&&<Dialog title="Excluir material" onClose={()=>setRemove(null)}><p>Excluir “{remove.title}” da biblioteca? O arquivo armazenado será preservado para recuperação.</p>{error&&<p role="alert">{error}</p>}<div className="flex justify-end gap-2 mt-6"><button className="button" onClick={()=>setRemove(null)}>Cancelar</button><button className="button btn-danger" disabled={deletion.isPending} onClick={()=>deletion.mutate()}>Excluir material</button></div></Dialog>}
 </div>
}
